# 1. Setup PHP, extensions, and Apache
[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.dom", "php82Extensions.fileinfo", "php82Extensions.zip", "php82Extensions.curl", "php82Extensions.tokenizer", "php82Extensions.xml", "apacheHttpd"]

# 2. Install composer dependencies
[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

# 3. Build the application (cache config, routes, etc.)
[phases.build]
cmds = [
    "php artisan optimize:clear",
    "php artisan optimize",
    "php artisan storage:link"
]

# 4. Deploy (run migrations, seeders, and fix permissions)
[phases.deploy]
cmds = [
    "php artisan migrate --force",
    "php artisan db:seed --force",
    "chown -R www-data:www-data /app/storage /app/bootstrap/cache",
    "chmod -R 775 /app/storage /app/bootstrap/cache"
]

# 5. Start the production server (Apache)
[start]
cmd = "heroku-php-apache2 public/"