# 1. Setup PHP extensions
[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.dom", "php83Extensions.fileinfo", "php83Extensions.zip", "php83Extensions.curl", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.intl"]

# 2. Install composer dependencies
[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

# 3. Build the application (cache config AND publish assets)
[phases.build]
cmds = [
    "php artisan optimize:clear",
    "php artisan vendor:publish --tag=filament-assets --force",
    "php artisan livewire:publish --assets",
    "php artisan optimize",
    "php artisan storage:link"
]

# 4. Deploy (EMPTY - this skips migrations)
[phases.deploy]
cmds = []

# THE [start] SECTION IS GONE.
# This forces Railway to use its default production server.