# 1. Setup PHP extensions
[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.dom", "php83Extensions.fileinfo", "php83Extensions.zip", "php83Extensions.curl", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.intl"]

# 2. Install composer dependencies
[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev"
]

# 3. Build the application (cache config, routes, etc.)
[phases.build]
cmds = [
    "php artisan optimize:clear",
    "php artisan optimize",
    "php artisan storage:link"
]

# 4. Deploy (run migrations and seeders)
[phases.deploy]
cmds = [
    "php artisan migrate --force",
    "php artisan db:seed --force"
]

# 5. Start the production server
[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"